spring:
  flyway:
    enabled: false
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/gtd
